// Generated by npm run build. Edit src/ instead.
// 각 설치 파일에 포함하되, 페이지에서는 같은 런타임/요청을 공유한다.
(function () {
  const key = "__IMWEB_PRODUCT_NOTICES_V1__";
  if (window[key]) return;
  const API_URL =
    "https://script.google.com/macros/s/AKfycbzHZKXnGomjSslR3C355roaWa7VYpcOdtzuAS7j9ZpT2QyGZAdf5OoYSqo5_DZRqBg/exec";
  const CACHE_URL =
    "https://imweb-notices-cache-4w4l3rcbpq-du.a.run.app/v1/rules";
  const aliases = {
    "neverseenbefore.imweb.me": "nvsbf.com",
    "dustystuff.imweb.me": "dustuff.co.kr",
    "lessbless.imweb.me": "lessbless.com",
    "roseu.imweb.me": "roseyou.kr",
    "ridiculous.imweb.me": "ridiculous.co.kr",
    "mascolino.imweb.me": "mascolino.co.kr",
    "sonador.imweb.me": "sonador.co.kr",
    "armykaji.imweb.me": "armykaji.com",
    "estrellas.imweb.me": "estrellas.co.kr",
    "worknwalk.imweb.me": "worknwalk.com",
    "closebye.imweb.me": "closeby2.com",
    "kissofsummer.imweb.me": "kissofsummer.co.kr",
  };
  const text = (value) =>
    String(value ?? "")
      .replace(/\s+/g, " ")
      .trim();
  const normalizeDomain = (value) =>
    text(value)
      .replace(/^https?:\/\//i, "")
      .replace(/^www\./i, "")
      .replace(/\/.*$/, "")
      .toLowerCase();
  const canonicalDomain = (value) => {
    const domain = normalizeDomain(value);
    return aliases[domain] || domain;
  };
  const productId = new URLSearchParams(location.search).get("idx") || "";
  const domain = canonicalDomain(location.hostname);
  const started = new Set();
  const ready =
    document.readyState === "loading"
      ? new Promise((resolve) =>
          document.addEventListener("DOMContentLoaded", resolve, {
            once: true,
          }),
        )
      : Promise.resolve();
  let request;

  const pageRequests = new AbortController();
  window.addEventListener("pagehide", (event) => {
    if (!event.persisted) pageRequests.abort();
  });

  function pause(ms, signal = pageRequests.signal) {
    return new Promise((resolve, reject) => {
      if (signal.aborted) return reject(new Error("안내 조회 종료"));
      const finish = () => {
        signal.removeEventListener("abort", cancel);
        resolve();
      };
      const cancel = () => {
        clearTimeout(timer);
        signal.removeEventListener("abort", cancel);
        reject(new Error("안내 조회 종료"));
      };
      const timer = setTimeout(finish, ms);
      signal.addEventListener("abort", cancel, { once: true });
    });
  }

  async function requestRules(endpoint, timeoutMs, cached = false, signal) {
    const url = new URL(endpoint);
    url.searchParams.set("domain", normalizeDomain(location.hostname));
    url.searchParams.set("productId", productId);
    // The normal endpoint omits automatic PACK/SET rules unless requested.
    if (!cached) url.searchParams.set("packs", "1");
    const controller = new AbortController();
    const cancel = () => controller.abort();
    signal.addEventListener("abort", cancel, { once: true });
    if (signal.aborted) cancel();
    const timeout = setTimeout(() => controller.abort(), timeoutMs);
    try {
      const response = await fetch(url.toString(), {
        cache: "no-store",
        signal: controller.signal,
      });
      if (!response.ok) throw new Error("API 응답 오류: " + response.status);
      const data = await response.json();
      if (!Array.isArray(data)) throw new Error("API 응답 형식 오류");
      if (cached) {
        const validUntil = Number(response.headers.get("X-Notice-Valid-Until"));
        if (!Number.isFinite(validUntil) || validUntil <= Date.now())
          throw new Error("안내 캐시 만료");
      }
      return data;
    } finally {
      clearTimeout(timeout);
      signal.removeEventListener("abort", cancel);
    }
  }

  async function fetchRound() {
    const round = new AbortController();
    const cancel = () => round.abort();
    pageRequests.signal.addEventListener("abort", cancel, { once: true });
    if (pageRequests.signal.aborted) cancel();
    // Keep the cache request alive for the server's bounded origin recovery.
    // At 1.8s start Google as a second path; do not discard the pending cache.
    const cached = requestRules(CACHE_URL, 12500, true, round.signal).then(
      (data) => ({ data, outcome: "CACHE" }),
    );
    try {
      const fast = await Promise.race([
        cached.catch(() => null),
        pause(1800, round.signal).then(() => null),
      ]);
      if (fast) return fast;
      const fallback = (async () => {
        for (let attempt = 0; attempt < 2; attempt++) {
          if (round.signal.aborted) throw new Error("안내 조회 종료");
          try {
            const data = await requestRules(API_URL, 8000, false, round.signal);
            return { data, outcome: "GOOGLE" };
          } catch (error) {
            if (attempt === 1 || round.signal.aborted) throw error;
          }
          await pause(250, round.signal);
        }
      })();
      return await Promise.any([cached, fallback]);
    } finally {
      round.abort();
      pageRequests.signal.removeEventListener("abort", cancel);
    }
  }

  async function fetchData() {
    const sampled =
      typeof navigator.sendBeacon === "function" && Math.random() < 0.1;
    const startedAt = performance.now();
    const report = (outcome) => {
      if (!sampled) return;
      try {
        navigator.sendBeacon(
          new URL("/v1/delivery", CACHE_URL).href,
          JSON.stringify({
            schema: 1,
            outcome,
            latencyMs: Math.min(
              60000,
              Math.max(0, Math.round(performance.now() - startedAt)),
            ),
          }),
        );
      } catch (_) {} // Observability cannot delay or fail the customer notice.
    };
    // Retry a shared read after transient failures/cooldown, so all features
    // can recover on the same page without a customer refresh. No stale data
    // or synthetic empty result is used to conceal an unavailable origin.
    for (let attempt = 0; attempt < 3; attempt++) {
      try {
        const { data, outcome } = await fetchRound();
        report(outcome);
        return data;
      } catch (error) {
        if (attempt === 2 || pageRequests.signal.aborted) {
          if (!pageRequests.signal.aborted) report("UNAVAILABLE");
          throw error;
        }
      }
      await pause(attempt === 0 ? 5000 : 10000);
    }
  }

  async function fetchRules() {
    return (await fetchData())
      .filter(
        (item) =>
          item &&
          typeof item === "object" &&
          !Array.isArray(item) &&
          item.enabled !== false &&
          (canonicalDomain(item.domain) === domain ||
            (Array.isArray(item.domainAliases) &&
              item.domainAliases.some(
                (alias) =>
                  normalizeDomain(alias) === normalizeDomain(location.hostname),
              ))) &&
          text(item.productId) === productId,
      )
      .sort((a, b) => (Number(b.priority) || 0) - (Number(a.priority) || 0));
  }

  function rules() {
    if (!request) request = fetchRules();
    return request;
  }

  function start(feature, init) {
    if (!/^\d+$/.test(productId) || started.has(feature)) return;
    started.add(feature);
    // Overlap the shared read with document loading; DOM work still waits below.
    rules().catch(() => {});
    ready
      .then(init)
      .catch((error) => console.error(feature + " 안내 불러오기 실패:", error));
  }

  function waitFor(selector, timeoutMs = 10000) {
    return new Promise((resolve) => {
      const found = document.querySelector(selector);
      if (found) return resolve(found);
      const finish = (element) => {
        observer.disconnect();
        clearTimeout(timer);
        window.removeEventListener("pagehide", leave);
        resolve(element);
      };
      const leave = (event) => {
        if (!event.persisted) finish(null);
      };
      const observer = new MutationObserver(() => {
        const element = document.querySelector(selector);
        if (element) finish(element);
      });
      const timer = setTimeout(() => finish(null), timeoutMs);
      observer.observe(document.body, { childList: true, subtree: true });
      window.addEventListener("pagehide", leave);
    });
  }

  window[key] = {
    version: 1,
    text,
    normalizeDomain,
    canonicalDomain,
    productId,
    domain,
    start,
    rules,
    waitFor,
  };
})();

(function () {
  const core = window.__IMWEB_PRODUCT_NOTICES_V1__;
  core.start("배송정보", async function () {
    const setting = (await core.rules()).find(
      (item) => core.text(item.type) === "배송정보" && core.text(item.message),
    );
    if (!setting) return;
    const delivery = await core.waitFor(".prod-detail-section--delivery");
    if (!delivery || document.querySelector('[data-sheet-notice="delivery"]'))
      return;
    const section = document.createElement("div");
    section.className =
      "prod-detail-section prod-detail-section--reserve-notice";
    section.dataset.sheetNotice = "delivery";
    const title = document.createElement("div");
    title.className = "prod-detail-section__title";
    title.textContent = "배송 정보";
    const content = document.createElement("div");
    content.className = "prod-detail-section__content";
    content.style.whiteSpace = "pre-wrap";
    content.style.overflowWrap = "anywhere";
    content.textContent = String(setting.message ?? "");
    section.append(title, content);
    delivery.insertAdjacentElement("afterend", section);
  });
})();

(function () {
  const core = window.__IMWEB_PRODUCT_NOTICES_V1__;
  core.start("구매혜택", async function () {
    const seen = new Set();
    const benefits = (await core.rules())
      .filter(
        (item) =>
          core.text(item.type) === "구매혜택" &&
          item.setupAvailable !== false &&
          !(
            item.setupLabel === "PACK_AUTO_V1" &&
            ["kissofsummer.co.kr", "mascolino.co.kr"].includes(core.domain)
          ) &&
          /^\d+$/.test(core.text(item.setupProductId)),
      )
      .filter((item) => {
        const id = core.text(item.setupProductId);
        if (seen.has(id)) return false;
        seen.add(id);
        return true;
      });
    if (!benefits.length) return;
    const detail = await core.waitFor("._item_detail_wrap");
    if (!detail) return;
    const currentTitle = document.querySelector("h1.view_tit");
    const currentName = getProductTitle(currentTitle);
    // 소유 표시가 있는 생성물만 교체한다. 상세 본문의 숨겨진 복제본은 필요하지 않다.
    detail
      .querySelectorAll('[data-sheet-benefit="true"]')
      .forEach((element) => element.remove());
    const fragment = document.createDocumentFragment();
    benefits.forEach((benefit) => {
      const counterpart =
        core.text(benefit.setupLabel) ||
        getCounterpartName(
          core.text(benefit.setupTitle),
          currentName || core.text(benefit.productName),
        );
      let message =
        core.text(benefit.message) ||
        "할인 받고 {상품명} 셋업으로 구매하러 가기→";
      message = message.replace(/\{상품명\}/g, () => counterpart || "세트상품");
      const discount = core.text(benefit.discount);
      if (benefit.setupLabel === "PACK_AUTO_V1") {
        // The signed API already constructs quantity and current public discount wording.
        if (
          core.text(benefit.productId) !== core.productId ||
          !Number.isFinite(Date.parse(benefit.endsAt)) ||
          Date.parse(benefit.endsAt) <= Date.now()
        )
          return;
      } else if (
        /^\d+(?:\.\d+)?%$/.test(discount) &&
        parseFloat(discount) > 0 &&
        parseFloat(discount) <= 100
      ) {
        message = discount + " " + message;
      } else {
        message = message.replace(/^할인\s*받고\s*/i, "");
      }
      const section = document.createElement("div");
      section.className = "benefit-wrap prod-detail-section benefit-injected";
      section.dataset.sheetBenefit = "true";
      section.style.display = "flex";
      const title = document.createElement("div");
      title.className = "prod-detail-section__title";
      title.textContent = "구매 혜택";
      const content = document.createElement("div");
      content.className = "prod-detail-section__content";
      const paragraph = document.createElement("p");
      paragraph.className = "prod-detail-section__item";
      const link = document.createElement("a");
      const url = new URL("/shop_view", location.origin);
      url.searchParams.set("idx", core.text(benefit.setupProductId));
      link.href = url.toString();
      link.textContent = message;
      paragraph.append(link);
      content.append(paragraph);
      section.append(title, content);
      fragment.append(section);
      if (benefit.setupLabel === "PACK_AUTO_V1")
        setTimeout(
          () => section.remove(),
          Math.max(1, Date.parse(benefit.endsAt) - Date.now()),
        );
    });
    const delivery = detail.querySelector(".prod-detail-section--delivery");
    if (delivery) {
      delivery.style.setProperty(
        "border-bottom",
        "1px solid rgba(30, 30, 30, 0.1)",
        "important",
      );
      delivery.style.setProperty("padding-bottom", "12px", "important");
    }
    detail.append(fragment);
  });

  function getCounterpartName(setupTitle, currentName) {
    const normalize = (name) =>
      core
        .text(name)
        .replace(/\s+SET$/i, "")
        .toLowerCase();
    const parts = setupTitle
      .replace(/\s+SET$/i, "")
      .split("/")
      .map(core.text)
      .filter(Boolean);
    const matched = parts.findIndex(
      (name) => normalize(name) === normalize(currentName),
    );
    // 일치가 확인될 때만 상대 구성품을 추출한다. 상품명 추측으로 잘못 연결하지 않는다.
    if (parts.length > 1 && matched >= 0)
      return parts.filter((_, index) => index !== matched).join(" / ");
    return setupTitle;
  }

  function getProductTitle(element) {
    if (!element) return "";
    const clone = element.cloneNode(true);
    clone.querySelectorAll(".ns-icon").forEach((badge) => badge.remove());
    return core.text(clone.textContent);
  }
})();
