// Generated by npm run build. Edit src/ instead.
// 각 설치 파일에 포함하되, 페이지에서는 같은 런타임/요청을 공유한다.
(function () {
  const key = "__IMWEB_PRODUCT_NOTICES_V1__";
  if (window[key]) return;
  const API_URL =
    "https://script.google.com/macros/s/AKfycbzHZKXnGomjSslR3C355roaWa7VYpcOdtzuAS7j9ZpT2QyGZAdf5OoYSqo5_DZRqBg/exec";
  const aliases = {
    "neverseenbefore.imweb.me": "nvsbf.com",
    "dustystuff.imweb.me": "dustuff.co.kr",
    "lessbless.imweb.me": "lessbless.com",
    "roseu.imweb.me": "roseyou.kr",
    "ridiculous.imweb.me": "ridiculous.co.kr",
    "mascolino.imweb.me": "mascolino.co.kr",
    "sonador.imweb.me": "sonador.co.kr",
    "armykaji.imweb.me": "armykaji.com",
    "estrellas.imweb.me": "estrellas.co.kr",
    "worknwalk.imweb.me": "worknwalk.com",
    "closebye.imweb.me": "closeby2.com",
    "kissofsummer.imweb.me": "kissofsummer.co.kr",
  };
  const text = (value) =>
    String(value ?? "")
      .replace(/\s+/g, " ")
      .trim();
  const normalizeDomain = (value) =>
    text(value)
      .replace(/^https?:\/\//i, "")
      .replace(/^www\./i, "")
      .replace(/\/.*$/, "")
      .toLowerCase();
  const canonicalDomain = (value) => {
    const domain = normalizeDomain(value);
    return aliases[domain] || domain;
  };
  const productId = new URLSearchParams(location.search).get("idx") || "";
  const domain = canonicalDomain(location.hostname);
  const started = new Set();
  const ready =
    document.readyState === "loading"
      ? new Promise((resolve) =>
          document.addEventListener("DOMContentLoaded", resolve, {
            once: true,
          }),
        )
      : Promise.resolve();
  let request;

  async function fetchRules() {
    const url = new URL(API_URL);
    url.searchParams.set("domain", normalizeDomain(location.hostname));
    url.searchParams.set("productId", productId);
    for (let attempt = 0; attempt < 2; attempt++) {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 8000);
      try {
        const response = await fetch(url.toString(), {
          cache: "no-store",
          signal: controller.signal,
        });
        if (!response.ok) throw new Error("API 응답 오류: " + response.status);
        const data = await response.json();
        if (!Array.isArray(data)) throw new Error("API 응답 형식 오류");
        return data
          .filter(
            (item) =>
              item &&
              typeof item === "object" &&
              !Array.isArray(item) &&
              item.enabled !== false &&
              (canonicalDomain(item.domain) === domain ||
                (Array.isArray(item.domainAliases) &&
                  item.domainAliases.some(
                    (alias) =>
                      normalizeDomain(alias) ===
                      normalizeDomain(location.hostname),
                  ))) &&
              text(item.productId) === productId,
          )
          .sort(
            (a, b) => (Number(b.priority) || 0) - (Number(a.priority) || 0),
          );
      } catch (error) {
        if (attempt === 1) throw error;
      } finally {
        clearTimeout(timeout);
      }
      await new Promise((resolve) => setTimeout(resolve, 250));
    }
  }

  function rules() {
    if (!request) request = fetchRules();
    return request;
  }

  function start(feature, init) {
    if (!/^\d+$/.test(productId) || started.has(feature)) return;
    started.add(feature);
    ready
      .then(init)
      .catch((error) => console.error(feature + " 안내 불러오기 실패:", error));
  }

  function waitFor(selector, timeoutMs = 10000) {
    return new Promise((resolve) => {
      const found = document.querySelector(selector);
      if (found) return resolve(found);
      const finish = (element) => {
        observer.disconnect();
        clearTimeout(timer);
        window.removeEventListener("pagehide", leave);
        resolve(element);
      };
      const leave = (event) => {
        if (!event.persisted) finish(null);
      };
      const observer = new MutationObserver(() => {
        const element = document.querySelector(selector);
        if (element) finish(element);
      });
      const timer = setTimeout(() => finish(null), timeoutMs);
      observer.observe(document.body, { childList: true, subtree: true });
      window.addEventListener("pagehide", leave);
    });
  }

  window[key] = {
    version: 1,
    text,
    normalizeDomain,
    canonicalDomain,
    productId,
    domain,
    start,
    rules,
    waitFor,
  };
})();

(function () {
  const core = window.__IMWEB_PRODUCT_NOTICES_V1__;
  core.start("배송정보", async function () {
    const setting = (await core.rules()).find(
      (item) => core.text(item.type) === "배송정보" && core.text(item.message),
    );
    if (!setting) return;
    const delivery = await core.waitFor(".prod-detail-section--delivery");
    if (!delivery || document.querySelector('[data-sheet-notice="delivery"]'))
      return;
    const section = document.createElement("div");
    section.className =
      "prod-detail-section prod-detail-section--reserve-notice";
    section.dataset.sheetNotice = "delivery";
    const title = document.createElement("div");
    title.className = "prod-detail-section__title";
    title.textContent = "배송 정보";
    const content = document.createElement("div");
    content.className = "prod-detail-section__content";
    content.style.whiteSpace = "pre-wrap";
    content.style.overflowWrap = "anywhere";
    content.textContent = String(setting.message ?? "");
    section.append(title, content);
    delivery.insertAdjacentElement("afterend", section);
  });
})();
